[tool.poetry]
name = "steamspam"
version = "0.1.0"
description = ""
authors = ["daniel sonbolian <dsal3389@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
selenium = "^4.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
